matchoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path("", views.index, name='index'),
    path("detail/", views.detail, name='detail'),
    path("results/", views.results, name='results'),
    path("main", views.index, name="main"),
    path('store_detail/', views.store_detail, name='store_detail'),
]

polls/models.py
from django.db import models

class Review(models.Model):
    store = models.CharField(max_length=100)
    review = models.TextField()
    prediction = models.TextField()


    def __str__(self):
        return self.review

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.views.decorators.cache import cache_page
import json
import openai
from ._crawling import crawl_reviews, to_df
from ._chat import recommand_traveling_site
from django.conf import settings
import pandas as pd
import time

from .models import Review

def index(request):
    context = {"title": 'Home'}
    print(request)

    return render(request, "polls/index.html", context)
    

    
def detail(request):
    return render(request, "polls/detail.html", {"title": 'question'})

# 이거 꼭 바꿔라!!!!!!!!!!!!! 안바꾸면 3대멸망 아래로 3대임 내 대는 아님
openai.api_key = settings.OPENAI_API_KEY
openai.api_key = settings.OPENAI_API_KEY



def results(request):



    if request.method == 'POST':
        global df
        # 요청 받아서 문구 만들기
        res = request.POST
        bot_message = recommand_traveling_site(res)
        #store_list = to_df().prediction
        

        # 추천한 여행지와 "맛집" 키워드를 함께 검색하여 크롤링
        keyword = '맛집'
        query = f"{bot_message} {keyword}"
        crawl_reviews(query)
        df = to_df()

        df_html = df.to_html(
                        columns=['store', 'review'],
                        index=False, na_rep="", bold_rows=True,
                        classes=["table", "table-hover", "table-processed"])
        
        store_list = to_df().store.unique().tolist()
        

        context = {
            'bot_message': bot_message, 
            'store_list' : store_list,
            'df_html' : df_html,}
        

        return render(request, 'polls/results.html', context)
    
    else:
        return render(request, 'loading.html')



def store_detail(request):

    store = request.GET.get('store')
    reviews = Review.objects.filter(store=store)

    # 가게 이름 가져오기
    store_name = df[df['store']==store]['store'].iloc[0]

    context = {
        'store': store_name,
        'reviews': reviews,
    }

    return render(request, 'polls/store_detail.html', context)


def give_survey(request):
    return render(request, 'give_survey.html')

polls/templates/polls/detail.html
<!DOCTYPE HTML>
{% load static %}
{% csrf_token %}
<html>
	<head>
		<title>MATCHOO</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'polls/assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="polls/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<a href="{% url 'polls:main' %}" class="logo">TEAM_MATCHOO</a>
					</header>

				<!-- Nav -->
					<nav id="nav">
						<ul class="links">
							<li><a href="{% url 'polls:main' %}">Home</a></li>
							<li class="active"><a href="">여행지 추천받기</a></li>
							<li><a href="elements.html">결과</a></li>
						</ul>
						<ul class="icons">
							<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
						</ul>
					</nav>

				<!-- Main -->
					<div id="main">
						<!-- Post -->
						{% csrf_token %}
							<section class="post">
								<header class="major">
									<span class="date">May 8, 2023</span>
									<h1>여행지 추천 받기!<br /></h1>
									<h4>For your wonderful life</h4>
									<p>설문조사 후 제출을 하면<br />
									성향에 맞는 여행지를 추천해드려요!<br />
									</p>
								</header>
								<!-- <h1>유형조사</h1> -->

								<form action="{% url 'polls:results' %}" method="post">
									{% csrf_token %}
									<ul>
										<li>
											<p>어떤 여행을 좋아하시나요?</p>
											<input type="radio" id="y" name="trip" value="동적인 여행을 좋아하" checked>
											<label for="y">동적인 여행</label>
											<input type="radio" id="n" name="trip" value="정적인 여행을 좋아하">
											<label for="n">정적인 여행</label>
										</li>
										<li>
											<p>도시를 좋아하시나요 자연을 좋아하시나요?</p>
											<input type="radio" id="city" name="type" value="도심을 좋아하" checked>
											<label for="city">도심을 좋아한다</label>
											<input type="radio" id="nature" name="type" value="자연경관을 좋아하">
											<label for="nature">자연을 좋아한다</label>
										</li>
										<li>
											<p>어떤 교통수단을 선호하시나요?</p>
											<p><input type="radio" id="drive" name="movement" value="자가용을 이용하" checked>
											<label for="drive">자가용</label>
											<input type="radio" id="walk" name="movement" value="대중교통 이나 도보를 이용하">
											<label for="walk">대중교통 이나 도보</label></p>
										</li>
										<li>
											<p>이색적인 여행과 평범한 여행중 어느 것을 선호하시나요?</p>
											<input type="radio" id="famous" name="pop" value="이색적인 여행을 좋아하" checked>
											<label for="famous">이색적인 여행</label>
											<input type="radio" id="rare" name="pop" value="남들 다 하는 평범한 여행을 좋아하">
											<label for="rare">평범한 여행</label>
										</li>
										<li>
											<p>혼자하는 여행과 함께하는 여행 중 어떤 것을 선호하시나요? </p>
											<input type="radio" id="alone" name="with" value="혼자하는 여행" checked>
											<label for="alone">혼자하는 여행</label>
											<input type="radio" id="tog" name="with" value="함께하는 여행을 좋아하">
											<label for="tog">함께하는 여행</label>
										</li>
										<li>
											<p>북적이는 지역명소 방문과 편안한 휴식 중 어떤 테마를 선호하시나요</p>
											<p><input type="radio" id="act" name="how" value="지역명소 방문을 좋아" checked>
											<label for="act">지역명소 방문</label>
											<input type="radio" id="rest" name="how" value="편안한 휴식을 좋아">
											<label for="rest">편안한 휴식</label></p>
										</li>
									</ul>
									<input type="submit" value="제출">
								</form>

								<p>여행은 사람을 즐겁게 만든다</p>
								<p>Life is Good </p>
							</section>

					</div>

				<!-- Footer -->
					<footer id="footer">
						{% csrf_token %}
						<section>
							<form method="post" action="#">
								<div class="fields">
									<div class="field">
										<label for="name">Name</label>
										<input type="text" name="name" id="name" />
									</div>
									<div class="field">
										<label for="email">Email</label>
										<input type="text" name="email" id="email" />
									</div>
									<div class="field">
										<label for="message">Message</label>
										<textarea name="message" id="message" rows="3"></textarea>
									</div>
								</div>
								<ul class="actions">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</form>
						</section>
						<section class="split contact">
							<section class="alt">
								<h3>Address</h3>
								<p>1234 Somewhere Road #87257<br />
								Nashville, TN 00000-0000</p>
							</section>
							<section>
								<h3>Phone</h3>
								<p><a href="#">(000) 000-0000</a></p>
							</section>
							<section>
								<h3>Email</h3>
								<p><a href="#">info@untitled.tld</a></p>
							</section>
							<section>
								<h3>Social</h3>
								<ul class="icons alt">
									<li><a href="https://twitter.com/?lang=ko" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="https://ko-kr.facebook.com/" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="https://www.instagram.com/" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="https://github.com/" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
								</ul>
							</section>
						</section>
					</footer>
			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE HTML>
{% load static %}
{% csrf_token %}

<html>
	<head>
		<title>MATCHOO</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'polls/assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="polls/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper" class="fade-in">

				<!-- Intro -->
				<div id="intro">
					<div class="logo" style="margin-bottom: 5rem;">
					<a href="{% url 'polls:index' %}">
						{{ store }}
					</a>
					</div>
					<h1>MATCHOO<br /> 
					사용자 설문 기반 여행지 및 맛집 추천 서비스
					</h1>						
					<p>여행지 추천 및 맛집 추천 서비스를 받아보세요!</p>
					<ul class="actions">
					<li>
						<a href="#header" class="button icon solid solo fa-arrow-down scrolly">Continue</a>
					</li>
					</ul>
				</div>


				<!-- Header -->
					<header id="header">
						<a href="{% url 'polls:main' %}" class="logo">Team_MATCHOO</a>
					</header>

				<!-- Nav -->
					<nav id="nav">
						<ul class="links">
							<li class="active"><a href="">Home</a></li>
							<li><a href="detail">여행지 추천받기</a></li>
							{% comment %} 결과창에 새로운 html 하나 넣고싶은데 마땅히 생각나는게 없어서 지금은 404오류가 남. {% endcomment %}
							<li><a href="give_survey.html">결과</a></li>
							
						</ul>
						<ul class="icons">
							<li><a href="https://twitter.com/?lang=ko" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="https://ko-kr.facebook.com/" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
							<li><a href="https://www.instagram.com/" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="https://github.com/" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
						</ul>
					</nav>

				<!-- Main -->
					<div id="main">

						<!-- Featured Post -->
							<article class="post featured">
								<header class="major">
									<span class="date">May 8, 2023</span>
									<a href="#" class="image main"><img src="{% static 'polls/images/matchoolog2.png' %}" alt="Matchoo" /></a >
									<!-- <h2><a href="#">What is MATCHOO?<br /> -->
									</a></h2>
									<p>사용자 설문 기반 여행지 추천 & 주변 지역 맛집 추천서비스</p>
								</header>
								<ul class="actions special">
									<li><a href="detail" class="button large">Let's MATCHOO!</a></li>
								</ul>
							</article>

						


					</div>

				<!-- Footer -->
					<footer id="footer">
						<section>
							<form method="post" action="#">
								<div class="fields">
									<div class="field">
										<label for="name">Name</label>
										<input type="text" name="name" id="name" />
									</div>
									<div class="field">
										<label for="email">Email</label>
										<input type="text" name="email" id="email" />
									</div>
									<div class="field">
										<label for="message">Message</label>
										<textarea name="message" id="message" rows="3"></textarea>
									</div>
								</div>
								<ul class="actions">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</form>
						</section>
						<section class="split contact">
							<section class="alt">
								<h3>Address</h3>
								<p>1234 Somewhere Road #87257<br />
								Nashville, TN 00000-0000</p>
							</section>
							<section>
								<h3>Phone</h3>
								<p><a href="#">(000) 000-0000</a></p>
							</section>
							<section>
								<h3>Email</h3>
								<p><a href="#">info@untitled.tld</a></p>
							</section>
							<section>
								<h3>Social</h3>
								<ul class="icons alt">
									<li><a href="https://twitter.com/?lang=ko" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="https://ko-kr.facebook.com/" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="https://www.instagram.com/" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="https://github.com/" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
								</ul>
							</section>
						</section>
					</footer>
			</div>

		<!-- Scripts -->
			<script src="{% static 'polls/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/browser.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/util.js' %}"></script>
			<script src="{% static 'polls/assets/js/main.js' %}"></script>

	</body>
</html>

polls/templates/polls/loading.html
{% extends 'base.html' %}

{% block content %}
  <div class="loading-container">
    <video src="{% static 'videos/loading.mp4' %}" autoplay loop ></video>
    <p>Loading...</p>
  </div>


{% endblock content %}

polls/templates/polls/results.html
<!DOCTYPE HTML>
{% load static %}
{% csrf_token %}
<!--
	Massively by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>MATCHOO</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'polls/assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="polls/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<a href="index" class="logo">MATCHOO</a>
					</header>

				<!-- Nav -->
					<nav id="nav">
						<ul class="links">
							<li><a href="{% url 'polls:main' %}">Home</a></li>
							<li><a href="{% url 'polls:detail' %}">여행지 추천받기</a></li>
							<li class="active"><a href="">결과</a></li>
						</ul>
						<ul class="icons">
							<li><a href="https://twitter.com/?lang=ko" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="https://ko-kr.facebook.com/" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
							<li><a href="https://www.instagram.com/" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="https://github.com/" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
						</ul>
					</nav>

				<!-- Main -->
					<div id="main">

						<!-- Post -->
							<section class="post">
								<header class="major">
									<div class="contents1"> 당신에게 추천된 지역은 <h1 style="display:inline">{{bot_message}}</h1> 입니다</div>
									<br>
									<br>
									<br>								
									<div class="result">  </div>
									
									<div class="main_text0">
										<div class="contents1_bold">{{bot_message}}의 맛집을 확인해보세요!</div>
										<div class="contents2">
											{% for store in store_list %}
												<li>{{store}}</li>
												<button id="new-page-button-{{forloop.counter}}">리뷰 확인하기</button>
												<script>
													document.getElementById("new-page-button-{{forloop.counter}}").addEventListener("click", function() {
														var storeName = "{{ store }}";
														window.open(`/store_detail/?store=${storeName}`, "_blank");
													});
											</script>
											{% endfor %}
									</div>
									</div>
								​
								​
									{% comment %} <div class="footer">
									<div>
									{{ df_html | safe}}
									<!--챗봇 심기 / 아니면 없애고-->
									</div>
									</div>
									</div> {% endcomment %}
								

		<!-- Scripts -->
			<script src="{% static 'polls/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/browser.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'polls/assets/js/util.js' %}"></script>
			<script src="{% static 'polls/assets/js/main.js' %}"></script>
	</body>
</html>

polls/templates/polls/store_detail.html
<!DOCTYPE HTML>
{% load static %}
{% csrf_token %}
<!--
	Massively by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>MATCHOO</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'polls/assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="polls/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
    <div id="wrapper">

        <header id="header">
          <a href="https://www.google.com/search?q={{ store }}" class="logo">{{ store }}</a>
        </header>
      


<!-- Nav -->
        <nav id="nav" style="margin-bottom: 50px;">
          <ul class="links">
            <li><a href="index">Home</a></li>
            <li><a href="generic.html">여행지 추천받기</a></li>
            <li class="active"><a href="results.html">결과</a></li>
          </ul>
          <ul class="icons">
            <li><a href="https://twitter.com/?lang=ko" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="https://ko-kr.facebook.com/" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
            <li><a href="https://www.instagram.com/" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="https://github.com/" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
          </ul>
        </nav>

        
        <!-- Main -->
        <style>
          h1, h2 {
            color: black;
          }
          .box h2 {
            margin: 0;
            text-align: center;
            font-size: 1.5rem;
            color: black;
          }
        
          .box p {
            margin: 1;
            color: black;
          }
          div {
            margin: 10px;
          }
          div.board {
            width: 48%;
            float: left;
            background: white;
            border-radius: 20px;
            {% comment %} box-sizing: border-box; {% endcomment %}

          }
            {% comment %} box-sizing: border-box; {% endcomment %}

          div.review {
            width: 90%;
            background: #f6f6f6;
            margin: 10px;
            padding: 20px;
            border-radius: 10px;
            float: center;
          }
          }
        </style>

<div class='white'>
<div class='board' style="padding:30px"; float: "left";>
    <h2>긍정리뷰</h2>
    {% for review in reviews %}
    
      {% if review.prediction == '긍정' %}
        <div class="review">
          {{ review.review }} 👍🏻
        </div>
      {% endif %}
      {% empty %}
        <p>긍정리뷰가 없습니다</p>
    {% endfor %}
</div>

<div class='board' style="padding:30px"; float: "right";>
    <h2>부정리뷰</h2>
    {% for review in reviews %}
    
      {% if review.prediction == '부정' %} 
        <div class="review">
          {{ review.review }} 👎🏻
        </div>
      {% endif %}
    
    {% empty %}
      <p>부정리뷰가 없습니다</p>
    {% endfor %}
</div>
</div>


		<!-- Scripts -->
      <script src="{% static 'polls/assets/js/jquery.min.js' %}"></script>
      <script src="{% static 'polls/assets/js/jquery.scrollex.min.js' %}"></script>
      <script src="{% static 'polls/assets/js/jquery.scrolly.min.js' %}"></script>
      <script src="{% static 'polls/assets/js/browser.min.js' %}"></script>
      <script src="{% static 'polls/assets/js/breakpoints.min.js' %}"></script>
      <script src="{% static 'polls/assets/js/util.js' %}"></script>
      <script src="{% static 'polls/assets/js/main.js' %}"></script>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'polls:index' %}">
                    <img 
                    src="https://postfiles.pstatic.net/MjAyMzA1MDZfOTcg/MDAxNjgzMzcxNjgxNTUz.sy-s7Ft6vNaFpByZmAaZ4NlqqHDd-BZi4wIiPQHLRc0g.dxQAXnDJFxcpICGJNVBo_5bLDMWokM0KNWv1ZWqWbW8g.PNG.hgkim51/logo_img.png?type=w773"
                    alt="Matchoo"
                    style="max-height:100%; width:auto;"
                     />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'polls:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'polls:detail' %}">설문 시작</a></li>
                    </ul>
                </div>
            </div>
        </nav>

    <hr>
    {% block content %}{% endblock content %}
</body>
</html>